config/routes.rb
Rails.application.routes.draw do

 devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
 }

 devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
 }

 scope module: :public do
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]
  
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'
  post 'orders/create' => 'orders#create'
  resources :orders, only: [:new, :index, :show]
  
  get 'customers/information' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/taikai' => 'customers#taikai'

 end

 namespace :admin do
  get root to: "homes#top"
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
 end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_one_attached :image
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items

  #enum is_active: { onsale: true, notsale: false }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
  accepts_nested_attributes_for :order_details
  
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + name + ' '
  end
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum product_status: { cannot: 0, wait: 1, now: 2, complete: 3 }
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
    <h4><%= @customer.last_name + @customer.first_name %>さんの情報編集</h4>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
      <table class="table table-md">
      <tr><th>会員ID</th><td><%= @customer.id %></td></tr>
      <tr><th>氏名</th><td class="d-flex flex-row"><%= f.text_field :last_name %><%= f.text_field :first_name %></td></tr>
      <tr><th>フリガナ</th><td class="d-flex flex-row"><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td></tr>
      <tr><th>郵便番号</th><td><%= f.text_field :postal_code %></td></tr>
      <tr><th>住所</th><td><%= f.text_field :address %></td></tr>
      <tr><th>電話番号</th><td><%= f.text_field :telephone_number %></td></tr>
      <tr><th>メールアドレス</th><td><%= f.text_field :email %></td></tr>
      <tr><th>会員ステータス</th>
      <td>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_delete, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_delete, "退会" %>
      </td></tr>
      </table>
      <div class="row">
      <div class="col-3"></div>
      <div class="col-4"><%= f.submit "変更を保存", class: 'btn btn-md btn-success' %></div>
      <div class="col-5"></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
      <h4>会員一覧</h4>
    </div>
  </div>
  
  <div class="row mt-3">
    <table class="table">
      <thead>
        <tr class="active">
          <th style="width: 20%">会員ID</th>
          <th style="width: 20%">氏名</th>
          <th style="width: 40%">メールアドレス</th>
          <th style="width: 20%">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to admin_customer_path(customer.id), class: "text-dark" do %><%= customer.last_name + customer.first_name %><% end %></td>
          <td><%= customer.email %></td>
          <td class="text-success font-weight-bold"><%= customer.is_deleted ? '退会' : '有効' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @customers %>
  </div>
  
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
    <h4><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h4>
    </div>  
  </div>
  <div class="row mt-5">
    <div class="col-3">
      <table class="table table-md">
      <tr><th>会員ID</th></tr>
      <tr><th>氏名</th></tr>
      <tr><th>フリガナ</th></tr>
      <tr><th>郵便番号</th></tr>
      <tr><th>住所</th></tr>
      <tr><th>電話番号</th></tr>
      <tr><th>メールアドレス</th></tr>
      <tr><th>会員ステータス</th></tr>
      </table>
    </div>
    <div class="col-5">
      <table class="table table-md">
      <tr><td><%= @customer.id %></td></tr>
      <tr><td><%= @customer.last_name + @customer.first_name %></td></tr>
      <tr><td><%= @customer.last_name_kana + @customer.first_name_kana %></td></tr>
      <tr><td><%= @customer.postal_code %></td></tr>
      <tr><td><%= @customer.address %></td></tr>
      <tr><td><%= @customer.telephone_number %></td></tr>
      <tr><td><%= @customer.email %></td></tr>
      <tr><td class="text-success font-weight-bold"><%= @customer.is_deleted ? '退会' : '有効' %></td></tr>
      </table>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-md btn-success' %>
    <%= link_to "注文履歴一覧を見る", root_path, class: 'btn btn-md btn-primary' %>
    </div>
  </div>
</div>
    