config/routes.rb
Rails.application.routes.draw do

 devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
 }

 devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
 }

 scope module: :public do
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]
  
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'
  post 'orders/create' => 'orders#create'
  resources :orders, only: [:new, :index, :show]
  
  get 'customers/information' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/taikai' => 'customers#taikai'

 end

 namespace :admin do
  get root to: "homes#top"
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
 end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_one_attached :image
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items

  #enum is_active: { onsale: true, notsale: false }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
  accepts_nested_attributes_for :order_details
  
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + name + ' '
  end
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum product_status: { cannot: 0, wait: 1, now: 2, complete: 3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row pt-3">
    <div class="bg-secondary">
    <h4>ジャンル編集</h4>
    </div>
  </div>
  
  <div class="row pt-4">
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name %>
      <%= f.submit '変更を保存', class: 'btn btn-md btn-success' %>
    <% end %>
  </div>

app/views/admin/genres/index.html.erb
<div class="container">
  
  <div class="row pt-3">
    <div class="bg-secondary">
      <h4>ジャンル一覧・追加</h4>
    </div>
  </div>
  
  <div class="row pt-4">
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name %>
      <%= f.submit '新規登録', class: 'btn btn-md btn-success' %>
    <% end %>
  </div>
  
  <div class="row pt-4">
    <div class="col-7">
      <table class="table">
        <thead>
            <th>ジャンル</th>
            <th></th>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <th><%= genre.name %></th>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-md btn-success' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-5"></div>
    
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
      <h4>商品編集</h4>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
    　<%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
      <table class="table table-md">
        <tr><th>商品画像</th><td><%= f.file_field :image, accept: "image/*" %></td></tr>
        <tr><th>商品名</th><td><%= f.text_field :name %></td></tr>
        <tr><th>商品説明</th><td><%= f.text_area :introduction %></td></tr>
        <tr><th>ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td></tr>
        <tr><th>税抜価格</th><td><%= f.number_field :price %>円</td></tr>
        <tr><th>販売ステータス</th>
        <td>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中" %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止中" %>
        </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row mt-2 mx-auto">
    <div class="col-5"></div>
    <div class="col-2">
    <%= f.submit "変更を保存", class: 'btn btn-md btn-success' %>
  　<% end %>
  　</div>
  　<div class="col-5"></div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  
  <div class="row mt-5 ml-3">
    <div class="col-3">
      <h4 class="text-center bg-secondary">商品一覧</h4>
    </div>
    <div class="col-8"></div>
    <div class="col-1">
      <%= link_to new_admin_item_path, class: "text-dark" do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>
    </div>
  </div>
  
  <div class="row mt-3">
    <div class="col-12">
      <table class="table">
        <thead>
          <th>
            <th style="width: 10%">商品ID</th>
            <th style="width: 30%">商品名</th>
            <th style="width: 10%">税抜価格</th>
            <th style="width: 30%">ジャンル</th>
            <th style="width: 20%">ステータス</th>
          </th>
        </thead>
        <% @items.each do |item| %>
        <tbody>
          <tr>
            <td></td>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id), class: 'text-dark' do %>
                <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %></td>
            <td><%= item.genre.name %></td>
            <td class="text-success font-weight-bold">
              <% if item.is_active == true %>
                <%= item.is_active = "販売中" %>
              <% else %>
                <%= item.is_active = "販売停止中" %>
              <% end %>
             </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row"></div>
  <div class="col-4"></div>
  <div class="col-4"><%= paginate @items %></div>
  <div class="col-4"></div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
      <h4>商品新規登録</h4>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-12">
    　<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
      <table class="table table-md">
        <tr><th>商品画像</th><td><%= f.file_field :image, accept: "image/*" %></td></tr>
        <tr><th>商品名</th><td><%= f.text_field :name %></td></tr>
        <tr><th>商品説明</th><td><%= f.text_area :introduction %></td></tr>
        <tr><th>ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td></tr>
        <tr><th>税抜価格</th><td><%= f.number_field :price %>円</td></tr>
        <tr><th>販売ステータス</th>
        <td>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中" %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止中" %>
        </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row mt-2 mx-auto">
    <div class="col-5"></div>
    <div class="col-2">
    <%= f.submit "新規登録", class: 'btn btn-md btn-success' %>
  　<% end %>
  　</div>
  　<div class="col-5"></div>
  </div>
</div>
    　

app/views/admin/items/show.html.erb
<div class="container">
  
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
      <h4>商品詳細</h4>
    </div>
  </div>
  
  <div class="row mt-5">
    <div class="col-5">
      <%= image_tag @item.get_image(300,300), class: "img-fluid" %>
    </div>
    <div class="col-7">
      <table class="table table-md">
        <tr><th>商品名</th><td><%= @item.name %></td></tr>
        <tr><th>商品説明</th><td><%= @item.introduction %></td></tr>
        <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
        <tr><th>税込価格(税抜価格)</th><td><%= (@item.price * 1.1).floor.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td></tr>
        <tr><th>販売ステータス</th>
        <td class="text-success font-weight-bold">
          <% if @item.is_active == true %>
            <%= @item.is_active = "販売中" %>
          <% else %>
            <%= @item.is_active = "販売停止中" %>
          <% end %>
        </td></tr>
      </table>
    </div>
  </div>
  
  <div class="row mt-3">
    <div class="col-5"></div>
    <div class="col-5"><%= link_to edit_admin_item_path(@item), class: 'btn btn-md btn-success' do %>編集する<% end %></div>
    <div class="col-5"></div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  
  <div class="row mt-5 ml-3">
    <div class="bg-secondary">
      <h4>注文履歴詳細</h4>
    </div>
  </div>
  
  <div class="row mt-3">
    <table class="table">
      <tr><th>購入者</th></th><td><%= @order.customer.last_name + @order.customer.first_name %></td></tr>
      <tr><th>注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td></tr>
      <tr><th>配送先</th><td><%= @order.my_address %></td></tr>
      <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
      <tr><th>注文ステータス</th><td></td></tr>
    </table>
  </div>

  <div class="row">
    
    <div class="col-9">
      <table class="table">
        <thead>
          <th>
            <th>商品</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
         <th></th>
          </th>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td></td>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price * 1.1).floor %></td>
            <td><%= order_detail.amount %></td>
            <td><%= (order_detail.item.price * 1.1).floor * order_detail.amount %></td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
            <td>
            <%= f.select :product_status, OrderDetail.product_statuses.keys.map { |k| [I18n.t("enums.order_detail.product_status.#{k}"), k]} %>
            </td>
            <td><%= f.submit "更新", class: 'btn btn-md btn-success' %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class="col-3">
      <table class="table">
        <tr><th>商品合計</th><td><%= @order.total_payment - 800 %></td></tr>
        <tr><th>送料</th><td>800</td></tr>
        <tr><th>請求金額合計</th><td><%= @order.total_payment %></td></tr>
      </table>
    </div>
    
  </div>
  
</div>