config/routes.rb
Rails.application.routes.draw do

 devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
 }

 devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
 }

 scope module: :public do
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  resources :items, only: [:index, :show]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]
  
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/complete' => 'orders#complete'
  post 'orders/create' => 'orders#create'
  resources :orders, only: [:new, :index, :show]
  
  get 'customers/information' => 'customers#show'
  get 'customers/information/edit' => 'customers#edit'
  patch 'customers/information' => 'customers#update'
  get 'customers/unsubscribe' => 'customers#unsubscribe'
  patch 'customers/taikai' => 'customers#taikai'

 end

 namespace :admin do
  get root to: "homes#top"
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :create, :show, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
 end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_one_attached :image
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items

  #enum is_active: { onsale: true, notsale: false }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  
  accepts_nested_attributes_for :order_details
  
  def my_address
    '〒' + postal_code + ' ' + address + ' ' + name + ' '
  end
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum product_status: { cannot: 0, wait: 1, now: 2, complete: 3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private
 def genre_params
   params.require(:genre).permit(:name)
 end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand navbar-dark">
        <%= link_to "LOGO", root_path, class: 'text-dark' %>
        <div class="collapse navbar-collapse justify-content-end" id="navmenu">
          <div class="navbar-nav">
          <% if admin_signed_in? %>
            <% if request.fullpath.include? "/admin" %>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "商品一覧", admin_items_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "会員一覧", admin_customers_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "注文履歴一覧", admin_root_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'text-dark'%>
                </button>
              </li>
            <% else %>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "About", about_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "商品一覧", about_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "新規登録", new_customer_registration_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログイン", new_customer_session_path, class: 'text-dark' %>
                </button>
              </li>
            <% end %>
          <% elsif customer_signed_in? %>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "マイページ", customers_information_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "商品一覧", items_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "カート", cart_items_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'text-dark' %>
                </button>
              </li>
          <% else %>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "About", about_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "商品一覧", about_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "新規登録", new_customer_registration_path, class: 'text-dark' %>
                </button>
              </li>
              <li class="nav-item nav-link active">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログイン", new_customer_session_path, class: 'text-dark' %>
                </button>
              </li>
          <% end %>
          <form class="d-flex h-75 mt-2">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success"><i class="fas fa-search"></i></button>
          </form>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>